# Generated by Django 5.0.3 on 2024-04-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_book_id_comments_name_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_creator',
            new_name='user',
        ),
    ]
