# Generated by Django 5.0.3 on 2024-04-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_book_comments_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
