[tool.poetry]
name = "my-expirience"
version = "0.1.0"
description = ""
authors = ["Maltseva Viktoria <malvicktoria2603@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
