# Generated by Django 5.0.3 on 2024-03-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
